#!/bin/bash
#
# Email Log Search
# Stanley Hammond - 2014
#
# This is a basic script that will search an email log file for a given  email address.
# This was original used to search log files generated by Ipswitch iMail Server, but should
# work for other mail server logs- in principle.
#
# This script is provided AS-IS.  I am not responsible for any damage this script my
# cause to your system.  Use it at your own risk.
#

if [ $# -lt 2 ]
then
	echo ""
    	echo "Syntax: $0 email_address path_and_name_of_logfile"
	echo "Example: $0 john_doe@example.com sample.log"
	exit
fi

email=$1
logs=$2

for messageid in `grep $email $logs | awk '{ print \$5 }' | uniq | sed 's/(//g;s/)//g'`
do
	grep $messageid $logs
	echo "-------------------------------------------------------------"
done
