#!/usr/bin/perl
#
# Web Log Parser
# Stanley Hammond - 2012-2013
#
# This script will create a CSV file of data from web logs generated by IIS.
# A scientist I was working for wanted to know who, where and when in regards to data
# that he was hosting for a grant he was working on.
#
# This script requires the Geo-IP module, which is available at:
# http://search.cpan.org/~maxmind/Geo-IP-1.45/lib/Geo/IP.pm
#
# This script was single focused so there are no variables that you can pass from the command line.
# File locations are hard coded in the script.  This script originally ran on a Linux server, that 
# had the IIS log files either copied to it or mounted as a directory.
#
# This script is provided AS-IS.  I am not responsible for any damage this script my
# cause to your system.  Use it at your own risk.
#

use Socket;
use Geo::IP;

# Set the following variables for your specific needs
$logfile_location = "Change to location of IIS logfiles";
$search_term = "Change to search expression you are looking for";
$output_location = "Change to location that you want to save the CSV file";

# Extract each address (host) in the given logfile based on the matched search expression and add it to the @addresses array
@addresses =`cat $logfile_location/*.log | grep $search_term | awk '{ print \$9 }' | sort | uniq -c | awk '{ print \$2 }'`;

# Open the CSV file at $output_location for writing
open(FILE, ">$output_location/web_data.csv");

# For each line in the @addresses array, do the following:
foreach $address (@addresses){
        chomp $address; # Remove the newline

	# Determine the IP address and hostname of the address 
        $ip_addr = inet_aton("$address");
        $host_name = gethostbyaddr($ip_addr, AF_INET);

	# Using Geo-IP module, determine where this address is located
        $gi = Geo::IP->open("/usr/local/share/GeoIP/GeoLiteCity.dat", GEOIP_STANDARD);
        $gi1 = Geo::IP->new(GEOIP_MEMORY_CACHE);
        $rec = $gi->record_by_addr($address);
        $country = $gi1->country_code_by_addr($address);
        $org = $gi1->name_by_addr($address);
        $lat = $rec->latitude;
        $long = $rec->longitude;
        $city = $rec->city;
        $reg = $rec->region;
        @whois = `whois $address`;

	# Determine the Internet Service Provider type (com, org, net, etc.) of the address from the whois information
        foreach $isp (@whois){
                if($isp =~ /OrgName:/) {
                        chomp $isp;
                        $isp =~ s/OrgName: +//g;
                        $x = $isp;
                }
                elsif($isp =~ /owner:/) {
                        chomp $isp;
                        $isp =~ s/owner: +//g;
                        $x = $isp;
                }
                #else{
                #       $x = "null";
                #}
        }

	# Print the IP address, Hostname, Country of origin, Location (longitude and latitude), City, Region and Type of organization
	# of address from file to both the display and write it to CSV file.
        print "$address\t$host_name\t$country\t$lat\t$long\t$city\t$reg\t$x\t$org\n";
        print FILE "$address,$host_name,$country,$lat,$long,$city,$reg,\"$x\",$org\n";
        undef($x);

}

# Close CSV file for writing
close(FILE);
